### ISSUE TITLE
Syntax error on install

### ISSUE THREAD

**Issue by schoeller** [mdbartos/pipedream#3]
Dear all,

thanks for your work. When doing ```python setup.py install``` on a fresh git pull, I receive the error

```
byte-compiling build/bdist.linux-x86_64/egg/superlink/superlink.py to superlink.pyc
  File "build/bdist.linux-x86_64/egg/superlink/superlink.py", line 1504
    r = b + np.squeeze(B @ u)
                         ^
SyntaxError: invalid syntax
```

I am running standard python interpreter ```Python 2.7.15+``` from Ubuntu 18.04.

Best regards

Sebastian

**Comment by mdbartos** [comment]
Hi Sebastian,

Thanks for your question. I didn't know that anyone was watching this repo. This code is mainly for personal research, so much of the code is not well-debugged or documented.

The `@` symbol is the matrix multiplication operator in python 3. Only python 3.6+ is supported at this stage.

I recently made a significant pull request to master, so it may be good to clone again if you want to experiment with this code.

I will be increasing documentation and test coverage in the next few weeks as I wrap up a paper that uses this code.
