### ISSUE TITLE
Initial guess for heads/flows

### ISSUE THREAD

**Issue by meghnathomas** [mdbartos/pipedream#68]
How would I go about providing an initial guess to the solver for flows in the superlinks and/or heads at superjunctions?

**Comment by mdbartos** [comment]
Thanks for this question.

- Initial depths in superjunctions can be provided via the `h_0` field in the superjunctions table.
- Initial flows in superlinks can be provided via the `Q_0` field in the superlinks table.
- Initial depths in junctions can be provided via the `h_0` field either in the superlinks table or in the junctions table if applicable.
- Initial flows in links can be provided via the `Q_0` field either in the superlinks table or in the links table if applicable.

Note that `h_0` refers to depth above the invert (or equivalent pressure) and not head here.

**Comment by meghnathomas** [comment]
Thank you!
